# -*- coding: utf-8 -*-
"""kawyaa

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mLn-t8gK3Mbhuim9AdJ6Q-itdSMeO4pj
"""

pip install word2number

import pandas as pd
df = pd.read_csv('hiring.csv')
print(df)

df['experience']=df['experience'].fillna('zero')
df

df['test_score(out of 10)'].fillna(0,inplace=True)
print(df.to_string())



x=df[['experience','test_score(out of 10)','interview_score(out of 10)']]
y=df['salary($)']
print(x.to_string())
print(y.to_string())

from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x,y)

ans=model.predict([[12,10,10]])
print(ans)

df = df.fillna(0)

df = df.replace({'five':5,'two':2,'seven':7,'three':3,'ten':10,'eleven':11})

df

df.info()

from sklearn.linear_model import LinearRegression
x = df.drop(columns=['salary($)'])
y = df['salary($)']

x

y

from sklearn.model_selection import train_test_split
model = LinearRegression()
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model.fit(X_train,y_train)

model.predict([[2,9,6]])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33)

print(x_train.shape)
print(x_test.shape)

finalans=LinearRegression()
finalans.fit(x_train,y_train)
ans=finalans.predict(x_test)
print(ans)

X = df.drop(columns=['salary($)'])
Y = df['salary($)']

n = int(input('Enter no of candidates : '))
for i in range(1,n+1):
    experience = int(input())
    test_score = int(input())
    interview_score = int(input())
    salary = model.predict([[int(experience),int(test_score),int(interview_score)]])
    print(salary)